### ISSUE TITLE
프로그램 설치 후 실행시 관리자 계정으로 실행해야 함

### ISSUE THREAD

**Issue by jbkim** [huinno-dev/patch_downloader#2]
어딘가에 설명이 필요함

**Comment by yubn** [comment]
C:\Program Files (x86) 폴더가 기본 관리자 권한이라 생기는 문제
기본 폴더 변경 방법 찾아보겠음

**Comment by yubn** [comment]
c 드라이브 시스템 폴더 제외하고 설치하도록 하면 관리자 권한 필요없이 실행 됨
