### ISSUE TITLE
프로그램 설치후 USB 드라이버 설치를 해야 함

### ISSUE THREAD

**Issue by jbkim** [huinno-dev/patch_downloader#3]
설치 프로그램에 드라이버까지 추가해서 같이 설치되도록 수정 필요함

**Comment by yubn** [comment]
다른 피씨(일반 윈도우 환경)에서 확인했을 때 추가적으로 드라이버 설치 필요 없었습니다.
실험 환경은 패치를 한번도 연결하지 않은 피씨 대상입니다.
확인부탁드립니다.

**Comment by jbkim** [comment]
예전에 윈도우즈에 드라이버를 설치해서 바로 사용이 된 줄 알았는데, 지우고 다시 연결하니 잡힙니다.
