### ISSUE TITLE
Open Folder 동작

### ISSUE THREAD

**Issue by jbkim** [huinno-dev/patch_downloader#5]
Open Folder 버튼은 연결이 되었을 때만 동작하는 것인지?
혹시 그렇다면 연결을 하지 않았을 때도 동작을 해야 할 것 같습니다.

**Comment by yubn** [comment]
프로그램 시작 시에 기본 경로 아래에 \Downloads 폴더 생성하여 해당 버튼으로 갈 수 있는 경로를 만들었습니다.
