### ISSUE TITLE
추가 요청 사항

### ISSUE THREAD

**Issue by jbkim** [huinno-dev/patch_downloader#7]
- 프로그램 설치후 설치된 폴더에가서 실행하는 것은 일반적이지 않은 것 같고, 왼쪽 설치된 항목(윈도우즈에서 이걸 뭐라고 부르는지 모름 ㅠㅠ)에 프로그램이 등록이 되야 할 것 같습니다.

- 로그를 지워주는 버튼이 있었으면 합니다.

**Comment by yubn** [comment]
데스크탑에 바로가기 아이콘 추가예정 (아이콘 이미지 화영님 제공)
로그 박스 클리어 버튼 추가
